# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Workshop(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, has_recurrence=None, has_host=None, has_end_time=None, description=None, has_location=None, id=None, label=None, type=None, has_start_time=None):  # noqa: E501
        """Workshop - a model defined in OpenAPI

        :param has_recurrence: The has_recurrence of this Workshop.  # noqa: E501
        :type has_recurrence: List[object]
        :param has_host: The has_host of this Workshop.  # noqa: E501
        :type has_host: List[object]
        :param has_end_time: The has_end_time of this Workshop.  # noqa: E501
        :type has_end_time: List[str]
        :param description: The description of this Workshop.  # noqa: E501
        :type description: List[str]
        :param has_location: The has_location of this Workshop.  # noqa: E501
        :type has_location: List[object]
        :param id: The id of this Workshop.  # noqa: E501
        :type id: str
        :param label: The label of this Workshop.  # noqa: E501
        :type label: List[str]
        :param type: The type of this Workshop.  # noqa: E501
        :type type: List[str]
        :param has_start_time: The has_start_time of this Workshop.  # noqa: E501
        :type has_start_time: List[str]
        """
        self.openapi_types = {
            'has_recurrence': List[object],
            'has_host': List[object],
            'has_end_time': List[str],
            'description': List[str],
            'has_location': List[object],
            'id': str,
            'label': List[str],
            'type': List[str],
            'has_start_time': List[str]
        }

        self.attribute_map = {
            'has_recurrence': 'hasRecurrence',
            'has_host': 'hasHost',
            'has_end_time': 'hasEndTime',
            'description': 'description',
            'has_location': 'hasLocation',
            'id': 'id',
            'label': 'label',
            'type': 'type',
            'has_start_time': 'hasStartTime'
        }

        self._has_recurrence = has_recurrence
        self._has_host = has_host
        self._has_end_time = has_end_time
        self._description = description
        self._has_location = has_location
        self._id = id
        self._label = label
        self._type = type
        self._has_start_time = has_start_time

    @classmethod
    def from_dict(cls, dikt) -> 'Workshop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Workshop of this Workshop.  # noqa: E501
        :rtype: Workshop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def has_recurrence(self):
        """Gets the has_recurrence of this Workshop.

        Description not available  # noqa: E501

        :return: The has_recurrence of this Workshop.
        :rtype: List[object]
        """
        return self._has_recurrence

    @has_recurrence.setter
    def has_recurrence(self, has_recurrence):
        """Sets the has_recurrence of this Workshop.

        Description not available  # noqa: E501

        :param has_recurrence: The has_recurrence of this Workshop.
        :type has_recurrence: List[object]
        """

        self._has_recurrence = has_recurrence

    @property
    def has_host(self):
        """Gets the has_host of this Workshop.

        Description not available  # noqa: E501

        :return: The has_host of this Workshop.
        :rtype: List[object]
        """
        return self._has_host

    @has_host.setter
    def has_host(self, has_host):
        """Sets the has_host of this Workshop.

        Description not available  # noqa: E501

        :param has_host: The has_host of this Workshop.
        :type has_host: List[object]
        """

        self._has_host = has_host

    @property
    def has_end_time(self):
        """Gets the has_end_time of this Workshop.

        Description not available  # noqa: E501

        :return: The has_end_time of this Workshop.
        :rtype: List[str]
        """
        return self._has_end_time

    @has_end_time.setter
    def has_end_time(self, has_end_time):
        """Sets the has_end_time of this Workshop.

        Description not available  # noqa: E501

        :param has_end_time: The has_end_time of this Workshop.
        :type has_end_time: List[str]
        """

        self._has_end_time = has_end_time

    @property
    def description(self):
        """Gets the description of this Workshop.

        small description  # noqa: E501

        :return: The description of this Workshop.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Workshop.

        small description  # noqa: E501

        :param description: The description of this Workshop.
        :type description: List[str]
        """

        self._description = description

    @property
    def has_location(self):
        """Gets the has_location of this Workshop.

        Description not available  # noqa: E501

        :return: The has_location of this Workshop.
        :rtype: List[object]
        """
        return self._has_location

    @has_location.setter
    def has_location(self, has_location):
        """Sets the has_location of this Workshop.

        Description not available  # noqa: E501

        :param has_location: The has_location of this Workshop.
        :type has_location: List[object]
        """

        self._has_location = has_location

    @property
    def id(self):
        """Gets the id of this Workshop.

        identifier  # noqa: E501

        :return: The id of this Workshop.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Workshop.

        identifier  # noqa: E501

        :param id: The id of this Workshop.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this Workshop.

        short description of the resource  # noqa: E501

        :return: The label of this Workshop.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Workshop.

        short description of the resource  # noqa: E501

        :param label: The label of this Workshop.
        :type label: List[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this Workshop.

        type of the resource  # noqa: E501

        :return: The type of this Workshop.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Workshop.

        type of the resource  # noqa: E501

        :param type: The type of this Workshop.
        :type type: List[str]
        """

        self._type = type

    @property
    def has_start_time(self):
        """Gets the has_start_time of this Workshop.

        Description not available  # noqa: E501

        :return: The has_start_time of this Workshop.
        :rtype: List[str]
        """
        return self._has_start_time

    @has_start_time.setter
    def has_start_time(self, has_start_time):
        """Sets the has_start_time of this Workshop.

        Description not available  # noqa: E501

        :param has_start_time: The has_start_time of this Workshop.
        :type has_start_time: List[str]
        """
        if has_start_time is not None and len(has_start_time) > 1:
            raise ValueError("Invalid value for `has_start_time`, number of items must be less than or equal to `1`")  # noqa: E501

        self._has_start_time = has_start_time
